server {
    listen 80;
    root /usr/share/nginx/html;
    index login.html register.html tasks.html;

    # Статические файлы
    location ~* \.(css|js|png|jpg|ico)$ {
        expires 1d;
        add_header Cache-Control "public, immutable";
    }

    # API - №1 по приоритету!
    location /api/ {
        
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Content-Length $content_length;  # ← НОВОЕ!
        proxy_pass_request_body on; 
        # ✅ РАЗРЕШЕНИЕ ВСЕХ МЕТОДОВ
        limit_except GET POST PATCH DELETE OPTIONS {
            deny all;
        }
    }

    # HTML - №2 по приоритету (ПОСЛЕ API)
    location = /login { 
        try_files /login.html =404; 
    }
    location = /register { 
        try_files /register.html =404; 
    }
    location = /tasks { 
        try_files /tasks.html =404; 
    }

    location / {
        try_files $uri $uri/ /login.html;
    }
}
